name: Qualys CloudView IaC Security JG
on:
  workflow_dispatch
#   push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main 
#  schedule:
#    - cron:  '0 */2 * * *'
jobs:
    Qualys_iac_scan:
        runs-on: ubuntu-latest
        name: Qualys IaC Scan
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
    
          - name: Qualys IAC scan action step
            uses: Qualys/github_action_qiac@main
            id: qiac
            env:
                URL: ${{ secrets.URL }}
                UNAME: ${{ secrets.USERNAME }}
                PASS: ${{ secrets.PASSWORD }}
            with:
              directory: .
          
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            if: always() 
            with:
                 sarif_file: response.sarif
